name: Cloud Transformation
on:
  push:
    branches:
      - main

env:
  AWS_ARN: ${{ secrets.AWS_ARN }}
  TF_VERSION: 'latest'
  TF_WORKING_DIR: '.'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ARN }}
          aws-region: aws-region-1

      - name: Setup terraform    
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive
      
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform plan
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform apply
        run: terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}



